##
## EPITECH PROJECT, 2018
## Maths
## File description:
## 104intersection: Makefile
##

NAME	=	104intersection

all:
	chmod 777 $(NAME)
clean:
	chmod 666 $(NAME)

fclean: clean
	rm -rf __pycache__
